### ISSUE TITLE
Getting the following error when activating the plugin

### ISSUE THREAD

**Issue by leeharris** [khromov/wp-wpml-geoip-browser-language-redirect#10]
Hey there,

I followed the steps and get the following error when trying to activate the plugin:

Parse error: syntax error, unexpected '[' in /wp-content/plugins/wp-wpml-geoip-browser-language-redirect-master/wpml-geoip-browser-language-redirect.php on line 95

;o)

**Comment by khromov** [comment]
Should work with the changes added in @79ea06d20e27798b7f5e565de33a167190819e7c
