### ISSUE TITLE
Its not working

### ISSUE THREAD

**Issue by mastercho** [khromov/wp-wpml-geoip-browser-language-redirect#12]
Im using WPML 3.3.5 version, i setup as your read me,
its not working and after i enable debug from js file i got  this error on console

Uncaught TypeError: Cannot read property 'log' of undefined browser-redirect-geoip.js:23

Please fix your plugin man!

**Comment by khromov** [comment]
@mastercho When debugging is enabled, the script uses `console.log` to display debugging logic. This is a standard approach and if you have some code that override `console.log` you need to remove it first. (For example by switching to a default theme like Twenty Eleven).

https://github.com/khromov/wp-wpml-geoip-browser-language-redirect/blob/master/js/browser-redirect-geoip.js#L23

**Comment by khromov** [comment]
@mastercho If you figure out what the problem is, feel free to post the debug log in a new issue.
