### ISSUE TITLE
You dont take serious the bug....

### ISSUE THREAD

**Issue by mastercho** [khromov/wp-wpml-geoip-browser-language-redirect#13]
Ok you closed my recent ticked, so i install fresh wordpress whit WPML and your plugin, opened from fresh installed firefox because i have some extensions on chrome, and still same problem.

Uncaught TypeError: Cannot read property 'log' of undefined browser-redirect-geoip.js:23

But nevermind i see there's a lot of reports not only in git you have it also in your official website comments that its not working and you are keep saying its working. But its not. Probably you are not have time to check it. Just mark plugin as non-working...

**Comment by khromov** [comment]
@mastercho The plugin works fine for me and many other people, but it's not an "activate it and forget it" solution, it might require additional configuration or adaption to your specific environment. 

It's impossible to provide support if you can't even get the javascript console to work, but if you do, feel free to post any issues you are having.

**Comment by mastercho** [comment]
Tell me which version of wpml you use and what theme so i can try it

**Comment by mastercho** [comment]
Also which version of wordpress ?

**Comment by 7wonders** [comment]
I have WPML 3.3.6 with x theme, latest WP etc and it works great. Slight delay in the redirect but otherwise flawless.

**Comment by mastercho** [comment]
I have removed WPML 3.3.5 and install WPML 3.3.6 but was still same, so next what i done was to remove redirect plugin and reupload & install it again, after this magic happen its redirected me to country based IP so i refresh ta page to see is working good? But after i reload the page for second time its not redirected me, i clean cache and cookies and wait 30 min and try it again and again redirected me once and after reload stop working, strange why is just 1 time is redirected with slight delay.

**Comment by khromov** [comment]
Sounds like you got it working @mastercho !

The reason for performing only a single redirect is to not force the user into a specific language. This mimics the default WPML implementation.

For more on the reasoning, see:
https://github.com/khromov/wp-wpml-geoip-browser-language-redirect/pull/11#issuecomment-187177123

**Comment by mastercho** [comment]
So theres no way to force always country base ip?

**Comment by khromov** [comment]
@mastercho Forcing is a bad idea, but If you check that pull request, it contains changes to do that, but it's up to you to integrate them if you want it.

**Comment by mastercho** [comment]
So if i add var forceRedirect  = true; on JS file will force them?

**Comment by khromov** [comment]
@mastercho No, but replacing the file `browser-redirect-geoip.js` with the proposed changeset should get you there.

https://github.com/khromov/wp-wpml-geoip-browser-language-redirect/blob/c172bae1532151e7719218cbc3e07e97b996ee63/js/browser-redirect-geoip.js

**Comment by mastercho** [comment]
Okay thank you my friend.
