### ISSUE TITLE
ReferenceError: browserLanguage is not defined

### ISSUE THREAD

**Issue by andrekutianski** [khromov/wp-wpml-geoip-browser-language-redirect#15]
The file `browser-redirect-geoip.js` is returning the information:

> Uncaught ReferenceError: browserLanguage is not defined
> (anonymous function) 
> @ browser-redirect-geoip.js?ver=4.5.3:65i 
> @ jquery.js?ver=1.12.4:2fireWith 
> @ jquery.js?ver=1.12.4:2ready 
> @ jquery.js?ver=1.12.4:2K 
> @ jquery.js?ver=1.12.4:2

and `https://www.domain.com/?wpml_geoip=1` return a 500 error.

The redirection don't occur

WP version 4.5.3 and WPML with the latest version

**Comment by uptimex** [comment]
I think it is related to this [https://github.com/khromov/wp-wpml-geoip-browser-language-redirect/issues/22](url)
