### ISSUE TITLE
Redirection not working

### ISSUE THREAD

**Issue by 383creative** [khromov/wp-wpml-geoip-browser-language-redirect#17]
Installed plugin and changed language mapping arrays. Testing from a GB IP Address and I should have been redirected to /gb language code but no redirection takes place. Site hosted with Pantheon.

![image](https://cloud.githubusercontent.com/assets/2375207/21108440/18d7f8ce-c063-11e6-9b96-26779b6d47fc.png)

![image](https://cloud.githubusercontent.com/assets/2375207/21108454/26b65760-c063-11e6-8409-a35d39e1197d.png)

![image](https://cloud.githubusercontent.com/assets/2375207/21108469/3328b89e-c063-11e6-87db-b4dbefeff509.png)

Turned the debug to true and get the following message in console.

![image](https://cloud.githubusercontent.com/assets/2375207/21108724/3181ac5c-c064-11e6-8788-39b3190b0327.png)

**Comment by khromov** [comment]
Hi,

This looks a little crazy, `console.log` is a standard function yet it's not available here. Can you try using a different browser, and if that doesn't work, can you try using a standard theme and disable any plugins you are running. (Alternatively, try running this plugin on a clean WP install with Twenty Sixteen, WPML and this plugin only and see if that resolves the issue.)

**Comment by 383creative** [comment]
Ok so since we're on Pantheon it was easy for me to spin up a clean WP install. All I installed was WPML and your plugin. 

![image](https://cloud.githubusercontent.com/assets/2375207/21109839/cc1bbdf8-c068-11e6-9e64-c85750263bf5.png)

WPML Languages Enabled:

![image](https://cloud.githubusercontent.com/assets/2375207/21109877/f6308f56-c068-11e6-958b-46e707c32c12.png)


Still seem to be getting the console error for log. 

Chrome:

![image](https://cloud.githubusercontent.com/assets/2375207/21109748/6b6d3522-c068-11e6-9805-e9cba3c335e8.png)

Firefox also returned an error:

![image](https://cloud.githubusercontent.com/assets/2375207/21109800/9ee32042-c068-11e6-8f40-76ad1a8e848f.png)

**Comment by 383creative** [comment]
I was able to get the console.log stuff to print by removing the IF statements.

![image](https://cloud.githubusercontent.com/assets/2375207/21150205/27302b16-c12c-11e6-8fbe-ba27e0e3a7e3.png)

As you can see, it thinks I'm in the US. I might be way off on this but I believe it's because Pantheon/Varnish doesn't return the clients true IP true, unless you use ($_SERVER['REMOTE_ADDR']) to get the IP?

See this thread on a similar plugin - https://wordpress.org/support/topic/geotargeting-problem/

**Comment by khromov** [comment]
@383creative Sounds like it. What is the response if you type the following URL in your browser: `http://example.com/?wpml_geoip=1` - it should tell you which country the plugin thinks you're in.

The plugin first checks for `$_SERVER['HTTP_X_FORWARDED_FOR']` (which is what a caching proxy would typically use) and then falls back to `$_SERVER['REMOTE_ADDR']`. 

You can try checking with Pantheon what they actually use. If they use another header, we can add it in to support it.

**Comment by 383creative** [comment]
Ahh thanks for the ?wpml_geoip=1 trick. It shows me as country code en (which is not the case). In order to get the correct IP what should we change? Is it this part in wpml-geoip-browser-language-redirect.php?

function register_endpoints()
	{
		if(intval(get_query_var('wpml_geoip')) == 1)
		{
			include('WPML_GeoIP_IPResolver.class.php');
			$ipr = new WPML_GeoIP_IPResolver();

			$ipr->set_json_header();
			if (array_key_exists('HTTP_X_FORWARDED_FOR', $_SERVER)) {
				$tmp_ip_array = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR']);
				$tmp_ip = $tmp_ip_array[0];
			} else {
				$tmp_ip = $_SERVER['REMOTE_ADDR'];
			}
			echo $ipr->ip_to_wpml_country_code($tmp_ip);
			die();
		}
	}

**Comment by 383creative** [comment]
I did this:

`
function register_endpoints()
	{
		if(intval(get_query_var('wpml_geoip')) == 1)
		{
			include('WPML_GeoIP_IPResolver.class.php');
			$ipr = new WPML_GeoIP_IPResolver();

			$ipr->set_json_header();

				$tmp_ip = $_SERVER['REMOTE_ADDR'];
			
			echo $ipr->ip_to_wpml_country_code($tmp_ip) . '<br>';
			echo $_SERVER['REMOTE_ADDR'];
			die();
		}
	}
}
`
And it returns the correct IP address, but still says EN. Perhaps the mappings are outdated?

**Comment by khromov** [comment]
@383creative Might be. What is the IP in question (you can hide the last octet) if you want.

**Comment by ryanyagin1902** [comment]
Hi @khromov 

We really appreciate your plugin to solve ip location redirect, we also encounter this same issue yet we were able to resolve this.  As our gratitude to your plugin please see what we updated on your code, hope this helps you in maintaining your plugin.

On ﻿wpml-geoip-browser-language-redirect.php, we updated the following:

1. On function __construct, we replace your action print_script to enqueue_scripts -- see below

/** Initialize and add actions */
	function __construct()
	{
		//Init script
		add_action( 'wp_enqueue_scripts',array($this, 'enqueue_scripts'), 10 );
		//add_action('wp_print_scripts', array(&$this, 'enqueue_scripts'), 100);

2. we had added register_script action on your function enqueue_scripts

/** Unload old browser redirect and add new one **/
	function enqueue_scripts()
	{
		global $sitepress, $sitepress_settings;

		//De-register old script
		wp_deregister_script('wpml-browser-redirect');

		//Register new one
		wp_register_script('jquery.cookie', ICL_PLUGIN_URL . '/res/js/jquery.cookie.js', array('jquery'), ICL_SITEPRESS_VERSION);

3. On the same function, we had added sitewpml on your params:

// Send params to javascript
		$params = array(
			'ajax_url' => plugins_url('ajax.php', __FILE__),
			'cookie'            => $cookie,
			'pageLanguage'      => defined('ICL_LANGUAGE_CODE')? ICL_LANGUAGE_CODE : get_bloginfo('language'),
			'languageUrls'      => $language_urls,
			'sitewpml'      => site_url() . '?wpml_geoip=1',
		);

4. Lastly, on your browser-redirect-geoip.js, your jquery with comment Get the country code to use IP, we replace data: to url :

//Get the country code to use by IP
                jQuery.ajax({
                    type: 'GET',
                    //data: {'wpml_geoip' : 1},
					url: wpml_browser_redirect_params.sitewpml,
                    async: false,
                    success: function (ret)
                    {
                        browserLanguage = ret.country_code
                    }
                });

Hope this helps

**Comment by khromov** [comment]
@ryanyagin1902 Please send these code changes as a [pull request](https://help.github.com/articles/about-pull-requests/), and I'd be happy to merge them.

**Comment by ryanyagin1902** [comment]
@khromov i created branch on my local copy but I cannot push it on your git
