### ISSUE TITLE
WPML API Hooks - replace "get_ls_languages" with more future-proof "wpml_active_languages"

### ISSUE THREAD

**Issue by andreasneuber** [khromov/wp-wpml-geoip-browser-language-redirect#18]
By the time this plugin was created WPML didn't provide yet the "WPML API Hooks" it has now - https://wpml.org/documentation/support/wpml-coding-api/wpml-hooks-reference/

Though there are no plans to deprecate the "get_ls_languages" method anytime soon, its more "future-proof" to replace it with WPML API hook "wpml_active_languages". https://wpml.org/wpml-hook/wpml_active_languages/

**Comment by khromov** [comment]
Thanks for the PR!

**Comment by andreasneuber** [comment]
You welcome :-)
