### ISSUE TITLE
browserLanguage returning null

### ISSUE THREAD

**Issue by jonheslop** [khromov/wp-wpml-geoip-browser-language-redirect#2]
Hey there,

The plugin isn’t on our dev site see — http://testeur.rapha.cc/service/returns
If you look in the console you’ll see I put in a few extra logs to `browser-redirect-geoip.js`

I see that the script looks up the country with an AJAX call is this what it calls — http://testeur.rapha.cc/?wpml_geoip=1 because that gives an error:

`
Fatal error: Cannot redeclare geoip_load_shared_mem() (previously declared in /apps/cms/rapha-wordpress/wp-content/plugins/wp-wpml-geoip-browser-language-redirect/lib/geoip-api-php/geoip.inc:241) in /apps/cms/rapha-wordpress/wp-content/plugins/wp-wpml-geoip-browser-language-redirect/lib/geoip-api-php/geoip.inc on line 257
`

I have declared my language mappings and default language, this is the file — http://jfh.cc/Udfx

Any help would be greatly appreciated

**Comment by khromov** [comment]
Hey @jonheslop, sorry for the delayed response.

It looks like everything is correct. The only way this would fail is if you are somehow  disallowing window.location from being changed, which can happen with some security extensions in web browsers. I would try this in a few other browsers and maybe a fresh Chrome install without extensions. Closing for now.
