### ISSUE TITLE
Add a settings page to make language mapping easier

### ISSUE THREAD

**Issue by andreasneuber** [khromov/wp-wpml-geoip-browser-language-redirect#20]
Actually "issue" is wrong term here, more a "nice to have".. :-) 

What about storing the country "code => language" combos and "default language mapping" in 2 wp options, and having a settings page for it? 
Would make setup/config easier (though current way is pretty easy, for users with coding skills).

![settings_page_1](https://cloud.githubusercontent.com/assets/20212159/23588309/702e5454-01c4-11e7-8640-d9eb80fc3bc9.png)
  
![settings_in_db_1](https://cloud.githubusercontent.com/assets/20212159/23588308/700f90be-01c4-11e7-84b4-37e7295fae23.png)

**Comment by andreasneuber** [comment]
For demo purposes: https://github.com/andreasneuber/wp-wpml-geoip-browser-language-redirect/tree/plugin_settings_page_demo_1  - branch: "plugin_settings_page_demo_1"

**Comment by khromov** [comment]
@andreasneuber Sounds like a great idea, similar to what I had planned for the plugin. If you add a PR I'd be happy to merge it.

**Comment by andreasneuber** [comment]
Happy to hear. I will polish it a bit more  and add a PR here then.

**Comment by khromov** [comment]
Closed via #21
