### ISSUE TITLE
Redirect not working: {"country_code":false}

### ISSUE THREAD

**Issue by pmjvanwijk** [khromov/wp-wpml-geoip-browser-language-redirect#23]
hi khromov,

thanks for this great plugin, unfortunately the redirect is not working for me.

When I visit https://www.mysite.com/?wpml_geoip=1, I get:

{"country_code":false}. 

I'm in Kenya.

My console returns this when I'm in debug mode:

Uncaught TypeError: Cannot read property 'log' of undefined
    at HTMLDocument.<anonymous> (browser-redirect-geoip.js?ver=4.8:23)
    at i (jquery.js?ver=1.12.4:2)
    at Object.fireWith [as resolveWith] (jquery.js?ver=1.12.4:2)
    at Function.ready (jquery.js?ver=1.12.4:2)
    at HTMLDocument.K (jquery.js?ver=1.12.4:2)
(anonymous) @ browser-redirect-geoip.js?ver=4.8:23
i @ jquery.js?ver=1.12.4:2
fireWith @ jquery.js?ver=1.12.4:2
ready @ jquery.js?ver=1.12.4:2
K @ jquery.js?ver=1.12.4:2

Do you know what could be wrong?

Many thanks!
Pieter

**Comment by khromov** [comment]
@pmjvanwijk Can you try updating your `GeoIP.dat` file and see if you still get `undefined` as your country code? You can find a new copy here: https://dev.maxmind.com/geoip/legacy/install/country/

**Comment by pmjvanwijk** [comment]
Hi Stanislav, thanks for your reply! Just installed the new version but it stays the same. Our website is https://charlies-travels.com.

**Comment by khromov** [comment]
@pmjvanwijk Must be some issue with the Maxmind library. Please check your server log for errors. This issue might be related: https://github.com/khromov/wp-wpml-geoip-browser-language-redirect/issues/2

**Comment by pmjvanwijk** [comment]
I turned debug mode on and I got this error message:
Warning: Invalid argument supplied for foreach() in /www/wp-content/plugins/wp-wpml-geoip-browser-language-redirect-master/WPML_GeoIP_IPResolver.class.php on line 71

This is line 71 in my file:
foreach($this->language_mappings as $maxmind_code => $wpml_code)

**Comment by khromov** [comment]
@pmjvanwijk I know @andreasneuber added an options page for the mappings a while back, did you configure them? :)

Related: https://github.com/khromov/wp-wpml-geoip-browser-language-redirect/issues/20

**Comment by pmjvanwijk** [comment]
I’m not sure what you mean but I’ve configured the mappings like this:

$this->language_mappings = array(
			'NL' => 'nl', //The Netherlands
			'DE' => 'de', //Germany
			'KE' => 'nl' //Kenya
		);

**Comment by khromov** [comment]
@pmjvanwijk Mappings are handled through the web UI now. The readme documentation is out of date. See the ticket I linked above. 😄

**Comment by pmjvanwijk** [comment]
Thanks! Good to know. I've reinstalled the plugin. I don't see any country codes in the settings menu.

<img width="324" alt="screen shot 2017-08-01 at 4 06 23 pm" src="https://user-images.githubusercontent.com/8825641/28826639-78a67aa6-76d3-11e7-95f9-e238ff4a220a.png">

**Comment by khromov** [comment]
@pmjvanwijk Do you have WPML installed and configured for these languages? In that case I'll have to ask @andreasneuber if perhaps the integration needs to be updated.

**Comment by pmjvanwijk** [comment]
Yep!
<img width="638" alt="screen shot 2017-08-01 at 4 19 57 pm" src="https://user-images.githubusercontent.com/8825641/28827147-4c277154-76d5-11e7-98e4-ab6b8c33edc2.png">

**Comment by khromov** [comment]
@pmjvanwijk Please try with the latest version from GitHub - @andreasneuber added patch to fix this.
