### ISSUE TITLE
Preventing user from entering another language once redirected

### ISSUE THREAD

**Issue by yujulio** [khromov/wp-wpml-geoip-browser-language-redirect#26]
Hi, is there any way to prevent the user from going to another language once redirected? 

I  have seen the user deleting the language code suffix from the URL once redirected to access to the main language but what if I dont want him to see it, is there any way to check if he tries to do this then he will be redirected again to his country language?

**Comment by khromov** [comment]
@yujulio Only redirecting on the first page load is the intended behaviour, we don't want to force users into a potential redirect loop or force them to use the site in a specific language based on their location.

You can modify the javascript code yourself to force redirection, it's not difficult. But I do not recommend it.
