### ISSUE TITLE
geoip_load_shared_mem( ) function exists in WMPL country detector

### ISSUE THREAD

**Issue by hardeep360** [khromov/wp-wpml-geoip-browser-language-redirect#6]
Hi,
geoip_load_shared_mem( ) function is already exist in WMPL country detector plugin so this makes the plugin to stop working. Admin please change the name of this function.

For the users who are using this plugin can simply deactivate the "WMPL country detector" plugin to start working language redirect.

Thanks
Hardeep

**Comment by khromov** [comment]
@hardeep360 I'll have a look at that. Feel free to submit a pull request if you are inclined.

WPML Country Detector seems to have the same functionality as this plugin, is there anything you are missing in their plugin?

**Comment by hardeep360** [comment]
Can you make a plugin which will work without language parameter in url?
Like http://example.com rather than http://example.com/?lang=en. I have done this in one site. Language is selecting based on country ip and then i put it in $_GET['lang'] in plugin's php file also save in session.
I used wp_rewrite trick. Like if page call is /products then i add silently /products/?lang=en in rewrites. But i am unable to make it as separate plugin + one thing more suppose you are in UK  and you have the url of CA. When you use it then it is showing 404 error because i removed redirect canonical filter which was showing ?lang=en parameter in url. Can we do this?

**Comment by hardeep360** [comment]
http://vagisil.com is the site where i am doing this functionality.

**Comment by hardeep360** [comment]
Yes you are right. Actually i was not known of this fact when i made this site. But here i am saying if a US region the page link is /products  and for CA page link is /productsca (anything other than US link). So if a US person opens same link /products in CA then site should show /productsca page. So here both the page url will be different and no SEO problem.

I will appreciate your help and thank you for reply as i know your time is very costly.

**Comment by khromov** [comment]
@hardeep360 All you have to do is create multiple variations of your pages (one for each language in WPML). Then you can use either this plugin or WPML:s own WPML Country Detector to redirect appropriately.

Closing this.
