### ISSUE TITLE
Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by sessbach** [khromov/wp-wpml-geoip-browser-language-redirect#8]
Hi,

I'm trying to use your plugin and run in some issues. I know managed to get the plugin almost running but still get the following error (console)
```
Uncaught TypeError: Cannot read property 'substr' of undefined 
```
browser-redirect-geoip.js?ver=4.0:94

I think the problem is somewhere here as the js does not get any browserlanguage back from the php.

```                   
success: function (ret)
                    {
                        browserLanguage = ret.country_code;
                        alert('BROWSERLANG: ' + browserLanguage);
                    }
```

browserLanguage just returns 'undefined'

Let me know if you need more information to provide any help…if you want to :)

thanks,
sven

**Comment by khromov** [comment]
Hey @sessbach ,

Please inspect the AJAX request that goes off to `yoursite.com?wpml_geoip=1`
(Make sure to clear cache before.)

Or, just go to that URL in the browser and see if you get any errors.

Maybe it will be the same error as in #6 ?

**Comment by sessbach** [comment]
I'm getting a 500 Internal Server. If I try to open the URL with the parameter ?wpml_geoip=1 I get the 500 as well.

I'm not using that Country Detector Plugin.

**Comment by khromov** [comment]
@sessbach Try to look in the error logs for the web server and PHP, that should give you an idea as how to proceed.

**Comment by sessbach** [comment]
Thank you. I think we are getting there. On the server error logs I see

```
PHP Fatal error:  Cannot redeclare geoip_country_code_by_name() in […]/geoip-api-php/geoip.inc
```

**Comment by khromov** [comment]
@sessbach I updated the code to check if the GeoIP library is already loaded before loading it again. Here is the changeset:
https://github.com/khromov/wp-wpml-geoip-browser-language-redirect/commit/7a2fcefa583aa467d13cf9c0363198251e78522b

You can download the new version here on GitHub from the master branch,

**Comment by sessbach** [comment]
Unfortunately this fix changes nothing.

If I check the existents of geoip_country_code_by_name() and geoip_country_name_by_name() in geoip.php I don't get a 500 error anymore. But the language is not detected.

**Comment by khromov** [comment]
@sessbach You should check to see if some other code is loading the Maxmind GeoIP database. (The PHP errors shold show it) I know WPML have recently done some changes that may possibly include it. 

There's also the aformentioned plugin:
https://wordpress.org/plugins/wpml-country-detector/

Closing this for now.
