### ISSUE TITLE
plugin cannot be activated, fatal error

### ISSUE THREAD

**Issue by iPasqualito** [khromov/wp-wpml-geoip-browser-language-redirect#9]
unexpected '[' on line 95:

$tmp_ip = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR'])[0];

changed it to $tmp_ip = explode(',', $_SERVER['HTTP_X_FORWARDED_FOR'][0]);

and it works.

kind regards

**Comment by khromov** [comment]
@iPasqualito The above code is PHP 5.4+ only, that's why you got the error. The way you have changed it doesn't retain the functionality.

**Comment by khromov** [comment]
Compatibility with PHP versions lower than 5.4 is now restored as per 79ea06d20e27798b7f5e565de33a167190819e7c
